packages/core/src/logger.ts, packages/core/src/public-api.ts
I've implemented the Logger interface as per the reference and the discussions in mobilejazz/harmony-reference#14 and mobilejazz/harmony-reference#15.
I'm not sure if the file should go at root level and also if we should separate the interface/error/implementation into separate files.
Let me know your suggestions.
=> Add Logger implementation

tsconfig.json
We need to use even older ES standard to be able to target old platforms.
=> Use ES5 target instead of ES6 for maximum browser compatibility

packages/core/src/repository/data-source/sql/raw-sql.data-source.ts
The current implementation is limiting all "getAll" queries to 10 rows. 
This is limiting us as we might want some business logic cases where we want to query all rows without limit, even if this is potentially harmful. We can always use a OffsetLImitPaginationQuery to limit results.
=> Removing offset limit limitation if where querery is not paginated

jest.config.js, package-lock.json, package.json, packages/core/tests/index.test.ts
**Resolves #13**. For now it just adds Jest and updates the NPM `validate` task so that apart from linting it also run tests.
A dummy test is added into the `core` package as an example.
=> Add test infrastructure

packages/core/src/repository/cache.repository.ts, packages/core/src/repository/data-source/data-source-mapper.ts, packages/core/src/repository/data-source/in-memory.data-source.ts, packages/core/src/repository/data-source/local-storage.data-source.ts, packages/core/src/repository/data-source/mock.data-source.ts, packages/core/src/repository/data-source/sql/raw-sql.data-source.ts, packages/core/src/repository/data-source/void.data-source.ts, packages/core/src/repository/interactor/delete-all.interactor.ts, packages/core/src/repository/repository-mapper.ts, packages/core/src/repository/single-data-source.repository.ts, packages/core/src/repository/void.repository.ts, packages/nest/src/oauth/data/repository/oauth-client.repository.ts, packages/nest/src/oauth/data/repository/oauth-token.repository.ts, packages/typeorm/src/typeorm.data-source.ts
Resolves #7. Following the proposal of mobilejazz/harmony-reference#8.
- I added `console.warn` deprecation messages where needed.
- When possible, I've moved the Queries handling to the `delete` method.
- In those cases (and some others) I've also forwarded the call to the `delete` method.
=> Add `deleteAll` deprecation notices

README.md, packages/core/package-lock.json, packages/core/src/repository/data-source/sql/raw-sql.data-source.ts, packages/core/src/repository/data-source/sql/sql-query-param-composer.ts, packages/core/src/repository/data-source/sql/sql-row-counter.data-source.ts, packages/core/src/repository/data-source/sql/sql.query.ts, packages/core/src/repository/index.ts, packages/nest/src/oauth/data/datasource/query/oauth-access-token.query.ts, packages/nest/src/oauth/data/datasource/query/oauth-client-id.query.ts, packages/nest/src/oauth/data/datasource/query/oauth-client.query.ts, packages/nest/src/oauth/data/datasource/query/oauth-refresh-token.query.ts, packages/nest/src/oauth/data/datasource/query/oauth-token-id.query.ts, packages/nest/src/oauth/data/datasource/query/oauth-user-id.query.ts
- Removed `orderByParams()` & `whereParams()`
- Change signature of `orderBy` & `whereSql`: removed `dialect?: SQLDialect` in favor of `params: SQLQueryParamComposer`
- Changed `SQLQueryParamComposer` to accept a value inside the method `next(param: any)`
- New method `getParams()` in `SQLQueryParamComposer`, which returns the list of params inserted via the `next(param)` method.
- Updated `RawSQLDataSource` to work with the new version of `SQLQueryParamComposer`
- Updated `SQLRowCounterDataSource` to work with the new version of `SQLQueryParamComposer`
- Updated `OAuth2` server to work with the new SQL Params paradigm
Issue: https://github.com/mobilejazz/harmony-typescript/issues/48
Note changes break backwards compatibility. This must be deployed on version 0.7.0 (incrementing Y) and …
=> New SQL Params paradigm

packages/core/src/repository/cache.repository.ts
Implement a fallback lambda on CacheOperation to allow ignoring validation as described in this issue: mobilejazz/harmony-reference#85
=> Implements cache operation fallback

packages/core/src/repository/data-source/sql/raw-sql.data-source.ts, packages/core/src/repository/data-source/sql/sql.query.ts
These values are always available so is **false** that they are optionals (remember: `T?` means `T | undefined`); with stricter TS compiler options (e.g. `strictNullCheck`) it asks to handle this possibly `undefined` value generating unnecessary boilerplate.
This is the false error this generates with `strictNullCheck`:
`Cannot invoke an object which is possibly 'undefined'. ts(2722)`
=> Remove optionals (`?`) from SQL query signatures

packages/core/src/helpers/index.ts, packages/core/src/helpers/safe-storage.ts, packages/core/src/repository/data-source/local-storage.data-source.ts, packages/core/src/repository/data-source/storage.data-source.ts, packages/core/src/repository/index.ts, packages/core/src/repository/query/query.ts
**This is a breaking change, the fix is easy though:**
- Now it throws `NotFoundError` instead of returning `null`
- Rename `LocalStorageDataSource` to `StorageDataSource`
- Add the desired [`Storage` implementation](https://developer.mozilla.org/en-US/docs/Web/API/Storage) as first parameter, usually `localStorage` or `sessionStorage`.
From: 
```ts
new LocalStorageDataSource()
```
To:
```ts
new StorageDataSource(localStorage)
```
- Rename `LocalStorageDataSource` to `StorageDataSource`, as this can be used with any `Storage` implementation (e.g. `LocalStorage`, `SessionStorage`…)
- Add `SafeStorage` helper (which fallbacks to an in-memory implementation) to handle incognito issues, see: https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/
- Handle `null` `getItem` …
=> Improve StorageDataSource

packages/core/src/repository/data-source/data-source.ts, packages/core/src/repository/interactor/put-all.interactor.ts, packages/core/src/repository/interactor/put.interactor.ts, packages/core/src/repository/repository.ts
- All `put` pipelines interfaces changed to explicitly define `undefined` as an union type.
- `Put/PutAll` interactors updated with the new signature
- Interface signatures changed to arrow functions so that projects in _strict_ mode benefit of better signature checking. See: [Stack Overflow](https://stackoverflow.com/questions/69807243/why-typescript-doesnt-enforce-interface-signature) & [TS docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types).
- Fixes #26.
=> Fix "put" pipeline signatures

examples/backend/src/domain/app.provider.ts, packages/core/src/repository/cache.repository.ts, packages/core/src/repository/data-source/data-source.ts, packages/core/src/repository/data-source/in-memory.data-source.ts, packages/core/src/repository/data-source/mock.data-source.ts, packages/core/src/repository/data-source/sql/raw-sql.data-source.ts, packages/core/src/repository/data-source/storage.data-source.ts, packages/core/src/repository/data-source/void.data-source.ts, packages/core/src/repository/repository-mapper.ts, packages/core/src/repository/repository.ts, packages/core/src/repository/single-data-source.repository.ts, packages/core/src/repository/void.repository.ts, packages/typeorm/src/typeorm.data-source.ts
Repurpose `Repository` & `DataSource` to allow a generic `T` so that it now expresses the combination of all three basic get/put/delete interfaces. Code simplified where possible.
Closes #88
=> Repurpose `Repository` & `DataSource` to express the combination of get/put/delete types

examples/backend/src/domain/app.provider.module.ts, packages/core/src/data/sql.dialect.ts, packages/core/src/data/sql.interface.ts, packages/core/src/helpers/utilities.ts, packages/nest/src/app/database.module.ts, packages/nest/src/app/filters/http-exception.filter.ts, packages/nest/src/app/oauth.module.ts
**:link: Asana: https://app.asana.com/0/1109863238977521/1203174773901429/f**
- Make `SQLInterface` & `SQLDialect` abstract so they can be used directly as injection tokens
- Change providers to reference these classes directly instead of using the strings
=> BACKEND-1429 :: Feature-Internal :: Use abstract classes for SQLInterface & SQLDialect (for DI)

examples/angular/angular.json, package-lock.json, package.json, packages/bugfender/package.json, packages/core/package.json, packages/nest/package.json
**Asana: https://app.asana.com/0/1109863238977521/1203249744541411/f**
- Move some `package.json` dependencies to sections that better fit their usage (peer, optional, dev).
- Make `harmony-core` `class-transformer` constraint so it allows wider range of versions; and move it to 'peerDeps' to avoid [issues with `class-transformer` metadata storage](https://github.com/typestack/class-transformer/issues/36#issuecomment-540543193)
- Move some `harmony-nest` to "optional" as they're only needed if certain features from `harmony-nest` are used
- Remove some unused packages
- When a dep is only needed for its types, move to `dev` section
=> FRONTEND-1411 :: Feature Internal :: Change harmony-core `class-transformer` dependency into a `peerDependency`

examples/angular/src/features/hacker-news-story/hacker-news-story.provider.module.ts, examples/angular/src/features/hacker-news-story/hacker-news-story.provider.ts, examples/backend/src/domain/app.provider.module.ts, examples/backend/src/domain/app.provider.ts, packages/angular/src/index.ts, packages/angular/src/public-api.ts, packages/angular/src/utilities.ts, packages/core/src/helpers/types.ts, packages/nest/src/app/utilities.ts
Asana task link: https://app.asana.com/0/1109863238977521/1203355492851215/f
**Merge / Pull request information:**
- Add `createAngularProviders` that simplifies glue code between a pure TS Harmony provider and the Angular module.
- This follows the same pattern to [`createNestProviders`](https://github.com/mobilejazz/harmony-typescript/blob/master/packages/nest/src/app/utilities.ts#L3)
---
=> FRONTEND-1215 :: Feature :: Add `createAngularProviders` in a similar way to `createNestProviders`

packages/angular/src/http-request.builder.ts, packages/core/src/helpers/types.ts
**Asana: https://app.asana.com/0/1109863238977521/1203450043003512/f**
- Fix `Type<T>`, so it matches Angular/Nest ones
- Relax `HttpRequestBuilder` return types
=> FRONTEND-3512 :: Bug :: Relax `Type<T>` and `HttpRequestBuilder` return types

packages/angular/src/http-request.builder.ts, packages/core/src/helpers/types.ts
**Asana: https://app.asana.com/0/1109863238977521/1203450043003523/f**
Fixes the following scenario, where the generic is an array:
=> FRONTEND-3523 :: Bug :: Fix `HttpRequestBuilder.setResponseConstructor` for array generics

examples/angular/package.json, examples/angular/src/features/hacker-news-story/domain/interactors/get-hacker-news-latest-ask-stories.interactor.ts, examples/angular/src/features/hacker-news-story/domain/interactors/get-hacker-news-story.interactor.ts, examples/angular/src/features/hacker-news-story/hacker-news-story.provider.module.ts, examples/angular/src/features/hacker-news-story/hacker-news-story.provider.ts, package-lock.json, packages/bugfender/package.json, packages/bugfender/src/bugfender.logger.ts, packages/core/src/helpers/logger/device-console.logger.ts, packages/core/src/helpers/logger/logger.ts, packages/core/src/helpers/logger/void.logger.ts
**Asana: https://app.asana.com/0/1109863238977521/1203172481263555/f**
- Merge `Logger` interface and `AbstractLogger` into an abstract `Logger`
- Make logging APIs compatible with `console.*`
- Add `withTag()` factory method. This creates a new logger from a logger, but with a "tag" applied. Tags are strings that are preprended to log messages.
- This can be a `string` or a `Type<T>`. [This is convenient (note that there aren't string quotes in `withTag()`)](https://github.com/mobilejazz/harmony-typescript/blob/de3b94b0a1cc4edd905b4b00cdf1744689b04a84/examples/angular/src/features/hacker-news-story/hacker-news-story.provider.ts#L93) as it allows to set a class as the tag and is refactor friendly (e.g. "rename symbol").
=> FRONTEND-3555 :: Feature :: Merge Logger & AbstractLogger and improve API

examples/angular/src/features/hacker-news-story/hacker-news-story.provider.ts, examples/backend/src/domain/app.provider.ts, packages/core/src/helpers/utilities.ts, packages/nest/src/oauth/oauth.sql.provider.ts
**Asana: https://app.asana.com/0/1109863238977521/1203203232807708/f**
- Removes `createCacheDecorator` in favor of self contained `Cached` decorator
- In practice, this means that the decorator can be just imported and used, no need to create a `Cached` instance for each class that uses it.
=> FRONTEND-7708 :: Feature Internal :: Remove `createCacheDecorator` in favor of self contained `Cached` decorator

package.json, packages/core/src/repository/data-source/in-memory.data-source.ts, packages/core/tests/repository/data-source/in-memory.data-source.test.ts
**Asana: https://app.asana.com/0/1109863238977521/1203172481263575/f**
- Change `InMemoryDataSource` internal storage to `Map`
- Add `InMemoryDataSource` missing test cases
- Set Jest `silent` so that `console.*` messages aren't reported
=> FRONTEND-3575 :: Feature Internal :: Refactor `InMemoryDataSource` to use `Map`

CHANGELOG.md, package-lock.json, packages/bugfender/package.json, packages/bugfender/src/bugfender.logger.ts
**Asana: https://app.asana.com/0/1109863238977521/1203409192207941/f**
- Remove `@bugfender/common` from `@mobilejazz/harmony-bugfender`. This package is for internal use by Bugfender SDKs; users shouldn't be using it. In some project this forced us to install `@bugfender/common`.
- Instead, use the re-exported types from `@bugfender/sdk`.
=> FRONTEND-7941 :: Bug :: Remove @bugfender/common requirement

.gitignore, CHANGELOG.md, package.json, packages/angular/package.json, packages/bugfender/package.json, packages/core/package.json, packages/nest/package.json, packages/typeorm/package.json
**Asana: https://app.asana.com/0/1109863238977521/1203624980108163/f**
- Remove `--contents dist` flag on root `publish` npm task
- Instead, set `files` property in packages (this limits what gets copied to the published pack)
- Copy README to package root, instead of `dist` folder
=> FRONTEND-8163 :: Bug :: Fix invalid `main` field error
